// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARh3mNISGmk4LjoOwyq_q5GKV3utzVHlc',
    appId: '1:1067764995266:web:42e88ad33dd0c9a9fc575b',
    messagingSenderId: '1067764995266',
    projectId: 'aihackaton-5120f',
    authDomain: 'aihackaton-5120f.firebaseapp.com',
    storageBucket: 'aihackaton-5120f.firebasestorage.app',
    measurementId: 'G-30EQ02C2YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-L2bEtAxOx5UcxFy6wyEWPon28xpmc8',
    appId: '1:1067764995266:android:8860381632d46bebfc575b',
    messagingSenderId: '1067764995266',
    projectId: 'aihackaton-5120f',
    storageBucket: 'aihackaton-5120f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVT6CRCLo6BqX2AeBZm3g9Ryykxdnff8',
    appId: '1:1067764995266:ios:646aef21979c78b9fc575b',
    messagingSenderId: '1067764995266',
    projectId: 'aihackaton-5120f',
    storageBucket: 'aihackaton-5120f.firebasestorage.app',
    iosBundleId: 'com.example.aihackaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVT6CRCLo6BqX2AeBZm3g9Ryykxdnff8',
    appId: '1:1067764995266:ios:646aef21979c78b9fc575b',
    messagingSenderId: '1067764995266',
    projectId: 'aihackaton-5120f',
    storageBucket: 'aihackaton-5120f.firebasestorage.app',
    iosBundleId: 'com.example.aihackaton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARh3mNISGmk4LjoOwyq_q5GKV3utzVHlc',
    appId: '1:1067764995266:web:4c4a3ce3d27e923dfc575b',
    messagingSenderId: '1067764995266',
    projectId: 'aihackaton-5120f',
    authDomain: 'aihackaton-5120f.firebaseapp.com',
    storageBucket: 'aihackaton-5120f.firebasestorage.app',
    measurementId: 'G-X29TRQY8BT',
  );
}
